# Generated by Django 4.2.4 on 2023-08-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_blog_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_post',
        ),
        migrations.AddField(
            model_name='blog_title',
            name='post',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
