# Generated by Django 4.2.4 on 2023-08-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
