# Generated by Django 4.2.4 on 2023-08-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_personal_information_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
