# Generated by Django 4.2.4 on 2023-08-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_personal_information_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesional_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=2000)),
            ],
        ),
    ]
