# Generated by Django 4.2.4 on 2023-08-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_profesional_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_name', models.TextField(max_length=2000)),
            ],
        ),
    ]
